<?php
$force_ssl='';
$dominio='localhost';
$nombre_del_centro='IES Monterroso';
$nombre_corto='Monterroso';
$codigo_del_centro='29680';
$email_del_centro='mgarcia39@gmail.com';
$director_del_centro='Director';
$jefatura_de_estudios='Jefe';
$secretario_del_centro='Secre';
$direccion_del_centro='Plaza Begines, 5';
$localidad_del_centro='Estepona';
$codigo_postal_del_centro='29680';
$telefono_del_centro='952802662';
$fax_del_centro='';
$curso_actual='2014/15';
$inicio_curso='2014-09-15';
$fin_curso='2015-06-23';
$usuario_smstrend='';
$clave_smstrend='';
$db='intranet';
$db_user='php';
$db_host='localhost';
$db_pass='camell';
$mantenimiento='0';
$mod_tic='1';
$mod_horario='1';
$mod_faltas='1';
$mod_bilingue='1';
$mod_transporte='1';
$mod_sms='0';
$mod_biblio='1';
$p_biblio='';
$mod_eval='1';
$mod_matriculas='1';
$raiz_dir='/Applications/MAMP/htdocs/intranet/';
$doc_dir='/Applications/MAMP/htdocs/intranet/varios/';
$fotos_dir='/tmp';
$num_administ='2';
$num_conserje='1';
$administ1='Administrativo 1';
$dnia1='12345671';
$idea1='1234567u';
$administ2='Administrativo 2';
$dnia2='12345672';
$idea2='1234567y';
$administ3='';
$dnia3='';
$conserje1='conserje';
$dnic1='1234567C';
$num_carrito='3';
$TIC_1='TIC nº 1';
$TIC_2='TIC nº 2';
$TIC_3='TIC nº 3';
$TIC_4='';
$TIC_5='';
$TIC_6='';
$TIC_7='';
$TIC_8='';
$TIC_9='';
$TIC_10='';
$TIC_11='';
$TIC_12='';
$TIC_13='';
$TIC_14='';
$TIC_15='';
$num_medio='3';
$medio1='Medio nº 1';
$medio2='Medio nº 2';
$medio3='Medio nº 3';
$medio4='';
$medio5='';
$medio6='';
$medio7='';
$medio8='';
$medio9='';
$medio10='';


$db_con = mysqli_connect($db_host, $db_user, $db_pass);
mysqli_select_db($db_con, $db);

function registraPagina($pagina,$host,$user,$pass,$base)
{
$db_con = mysqli_connect($host, $user, $pass);
mysqli_select_db($db_con, $base);
$id_reg = $_SESSION['id_pag'];
mysqli_query($db_con, "INSERT INTO reg_paginas (id_reg,pagina) VALUES ('$id_reg','$pagina')");	
}

